name: Machine Learning CI - Advance

on:
  push:
    branches: [ main ]

jobs:
  train-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub scikit-learn pandas joblib

    - name: Run Model Training
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        cd "MLProject (folder)"
        python modelling.py

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-hasil-training
        path: |
          MLProject (folder)/mlruns
          MLProject (folder)/model_manual.pkl
        retention-days: 1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        cd "MLProject (folder)"
        # LOGIKA FINAL: Mencari folder model di dalam mlruns secara otomatis
        MODEL_PATH=$(find mlruns -name "model" -type d | head -n 1)
        
        echo "Folder model ditemukan di: $MODEL_PATH"
        
        mlflow models build-docker \
          -m "$MODEL_PATH" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/zeny-arsya-fortilla-m251d5x2016:latest" \
          --install-mlflow
          
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/zeny-arsya-fortilla-m251d5x2016:latest
