name: Machine Learning CI - Advance

on:
  push:
    branches: [ main ]

jobs:
  train-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub scikit-learn pandas joblib

    - name: Run Model Training
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        # Masuk ke folder project Anda
        cd "MLProject (folder)"
        # Menjalankan training (ini akan menghasilkan folder 'model' di dalam sini)
        python modelling.py

    - name: Upload Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-file
        path: "MLProject (folder)/*.pkl"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        # KUNCI PERBAIKAN: Path harus lengkap ke folder 'model' hasil mlflow
        mlflow models build-docker \
          -m "MLProject (folder)/model" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/zeny-arsya-fortilla-m251d5x2016:latest" \
          --install-mlflow
          
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/zeny-arsya-fortilla-m251d5x2016:latest
